include classpath("application.conf")

queues {
  ingest-queue {
    defaultVisibilityTimeout = 120 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "ingest-dlq"
      maxReceiveCount = 3
    }
  }
  ingest-dlq {}
}

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

rest-sqs-management {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}
